name: mensageria-minimal

networks:
  redpanda-network:
    driver: bridge

volumes:
  redpanda-data:

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.13
    container_name: mensageria-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --rpc-addr=redpanda:33145
      - --advertise-rpc-addr=redpanda:33145
      - --mode=dev-container
      - --smp=1
      - --default-log-level=warn
    ports:
      - "19092:19092"
      - "19644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - redpanda-network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info -X brokers=localhost:9092 >/dev/null 2>&1"]
      interval: 2s
      timeout: 2s
      retries: 30

  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.13
    container_name: mensageria-topic-init
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - redpanda-network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        rpk topic create support.ticket-events.v1 --brokers redpanda:9092 --partitions 3 --replicas 1 || true
        rpk topic create support.ticket-events.dlq.v1 --brokers redpanda:9092 --partitions 1 --replicas 1 || true
        rpk topic create support.ticket-events.integration.v1 --brokers redpanda:9092 --partitions 3 --replicas 1 || true

  console:
    image: docker.redpanda.com/redpandadata/console:v3.8.0
    container_name: mensageria-console
    depends_on:
      topic-init:
        condition: service_completed_successfully
    networks:
      - redpanda-network
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"]
    ports:
      - "8080:8080"
